### PR TITLE
Create alerting adr

### PR DESCRIPTION
**Pull request by mckornfield**
add an ADR for determining which monitoring soltion to use

### CODE REVIEW

**Review by ZavenArra — APPROVED** [review]

**Review by ZavenArra — CHANGES_REQUESTED** [review]
@mckornfield Please change the name of the file to include the next sequence ADR number, following what is currently in the PRs.  For instance, like this 0009-alerting.md

**Comment by mckornfield** [comment]
@ZavenArra done in the ui hehe

**Review by TANguyen1893 — APPROVED** [review]
LGTM

**Review by Kpoke — APPROVED** [review]
Looks good to me as well

**Review by ZavenArra — APPROVED** [review]
Looks great!  ADR accepted.

**Pull request merged**
