### PR TITLE
Use nosql db as supplement for postgresql

### PR DESCRIPTION
**Pull request by dadiorchen**
Technical Story: PostgreSQL is powerful relational DB and fits data storage for enterprise business. But there are cases on Greenstand that is more internet style and flavor, for example the poll system, the like system, for these cases, the characteristics of these case is: the data is not very complex, and the data is not very big, and the data is not very important, and the data is not very sensitive, but on the other hand, the data is very frequent, and the data is very dynamic, and the data is very easy to change. So we need to find a DB that is more suitable for these cases. (these two sentences are created by openAI, I think it goes my way, so I copy them here :) ), like the `like system`, it is an internet feature, it is possible that we will have millions of likes in the future, and also possible that thousands of users will click that `like` button at the same time, we don't want this kind of tiny feature to consume the resources of the PostgreSQL connections which are pretty limited and costly. So I think we can use no-sql like MongoDB to do a supplement to PostgreSQL.

### CODE REVIEW

**Comment by ZavenArra** [comment]
Mongo DB is known to have terrible scaling issues, and PostgresSQL is known to have resolved its scaling problems.  With thousands of clicks happening simultaneously, you would want to place a queue between the microservice and database to handle inserts on a worker thread at a clamped rate to flatten the burst.   So I recommend making use of queue services available in the existing infra rather than adding a new database technology.  In fact NoSQL is not longer as attractive of a solution as it was some years ago, as RDMS such as PostgreSQL have been updated to deal with larger volumes of records.

**Comment by dadiorchen** [comment]
Thanks, @ZavenArra, can you help consider this, the data is pretty less important than our regular data, just user click, it would be easy to get larger than our core data, and it feels not so relational, is it okay to put it into the main PostgreSQL, is it a bit costly for this kind of user data?

**Comment by ZavenArra** [comment]
What metrics are you using to evaluate 'cost' here?  In terms of speed, the indexing will be fine.  In terms of using Mongo DB, managing a new cloud service in the cloud certain creates costs in terms of labor and infra, and hosted Mongo DB solutions can become extremely expensive in my experience.

**Comment by dadiorchen** [comment]
In my understanding, the nosql is more underlying tech and don't need to handle relation table and transaction so supposed to be more low-cost, but I have no solid proof of this.

I feel the PostgreSQL hosted by digital ocean is pretty limited in terms of the connection pool, 100+ connections per instance, is it possible we can get a better performance on this by using some nosql, queue is a solution but we can not use it in all cases that we need the instant response? 

https://en.wikipedia.org/wiki/NoSQL#Performance

**Pull request closed without merging**
